modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "allthetrims"
version = "${version}"
displayName = "AllTheTrims"
authors = "Bawnorton"
description = '''
A mod that allows any item to be a trim material and makes all armour trimmable.
'''
#logoFile = ""

[[dependencies.allthetrims]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.allthetrims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.allthetrims]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"