modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/AllTheTrims/issues"
license = "MIT"

[[mods]]
modId = "allthetrims"
version = "${version}"
displayName = "AllTheTrims"
authors = "Bawnorton"
description = '''
A mod that allows any item to be a trim material and makes all armour trimmable.
'''
logoFile = "assets/allthetrims/icon.png"

[[dependencies.allthetrims]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"